version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d mydb']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: img-back
    environment:
      SPRING_APPLICATION_NAME: demo
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
    depends_on:
      db:
        condition: service_healthy
    #porst are ignored because of defaul.conf!!!
    ports:
      - '8080:8080'

  frontend:
    image:
      img-front
      #porst are ignored because of defaul.conf!!!!!
    ports:
      - '3000:3000'
    depends_on:
      - backend

  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - '4000:3000'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
