spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: user
    password: password
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop