spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: dev
        hbm2ddl:  
          create_namespaces: true
