spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: user
    password: password
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

# Debug with hibernate and jdbc")
logging:
  level:
    org.hibernate.SQL: DEBUG          # Mostra as queries SQL geradas
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Mostra os parâmetros das queries
    org.springframework.jdbc.datasource.init: DEBUG  # Logs de inicialização do banco